# Generated by Django 3.0.4 on 2020-03-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200314_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='AccessKey',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='EmailComercio',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='IDComercio',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='ModoIntegracion',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='Monto',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='NombreComercio',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='Pais',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='SecretKey',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='TiempoExpiracionPago',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='notification',
            name='TipoMoneda',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='ServidorPagoEfectivo',
            field=models.CharField(default='', max_length=25),
        ),
    ]
