# Generated by Django 3.0.4 on 2020-03-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200314_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServidorPagoEfectivo', models.CharField(default='', max_length=25)),
                ('AccessKey', models.CharField(default='', max_length=25)),
                ('SecretKey', models.CharField(default='', max_length=25)),
                ('IDComercio', models.CharField(default='', max_length=25)),
                ('NombreComercio', models.CharField(default='', max_length=25)),
                ('EmailComercio', models.CharField(default='', max_length=25)),
                ('ModoIntegracion', models.CharField(default='', max_length=25)),
                ('TiempoExpiracionPago', models.CharField(default='', max_length=25)),
                ('TipoMoneda', models.CharField(default='', max_length=25)),
                ('Monto', models.CharField(default='', max_length=25)),
                ('Pais', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='AccessKey',
            new_name='requestBody',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='EmailComercio',
            new_name='signature',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='IDComercio',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ModoIntegracion',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Monto',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='NombreComercio',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Pais',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='SecretKey',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ServidorPagoEfectivo',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='TiempoExpiracionPago',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='TipoMoneda',
        ),
    ]
