# Generated by Django 3.0.4 on 2020-03-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20200319_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='signature',
            field=models.CharField(default='', max_length=200),
        ),
    ]
